on: [push, pull_request]
name: Test
jobs:
  test:
    env:
      GOPATH: ${{ github.workspace }}

    defaults:
      run:
        working-directory: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}

    strategy:
      matrix:
        go-version: [1.18.x, 1.19.x]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
    - name: swagger
      run: |
        go install github.com/swaggo/swag/cmd/swag@v1.8.3
        swag init -d "./cmd/server" --parseDependency --parseDepth 1
    - name: Test
      run: |
        go get -d -t -v ./...
        go test -coverprofile=cover.out ./internal/app/...
        go tool cover -html=cover.out -o cover.html
    - name: coverage
      working-directory: ./src/github.com/${{ github.repository }}
      run: bash <(curl -s https://codecov.io/bash)